#!/bin/bash

# Deployment script for Cloud-Native MERN Hotel Booking System
# This script automatically detects the host IP and configures the environment

echo "🚀 Starting Cloud-Native MERN Hotel Booking System Deployment..."

# Function to detect the host IP address
get_host_ip() {
    # Try to get the IP address of the main network interface
    if command -v ip &> /dev/null; then
        # Linux with ip command
        HOST_IP=$(ip route get 8.8.8.8 | awk '{print $7}' | head -n1)
    elif command -v hostname &> /dev/null; then
        # Try hostname command
        HOST_IP=$(hostname -I | awk '{print $1}')
    else
        # Fallback to localhost
        HOST_IP="127.0.0.1"
    fi
    
    if [ -z "$HOST_IP" ] || [ "$HOST_IP" = "127.0.0.1" ]; then
        echo "⚠️  Could not auto-detect IP address. Using localhost."
        HOST_IP="localhost"
    fi
    
    echo "📍 Detected host IP: $HOST_IP"
}

# Check if user provided a custom host IP
if [ ! -z "$1" ]; then
    HOST_IP="$1"
    echo "📍 Using provided host IP: $HOST_IP"
else
    get_host_ip
fi

# Create/update the .env file
echo "📝 Configuring environment variables..."
cat > .env << EOF
# Docker Compose Environment Variables
# Auto-generated by deploy.sh on $(date)

API_HOST=http://$HOST_IP
EOF

echo "✅ Environment configured with API_HOST=http://$HOST_IP"

# Stop any existing containers
echo "🛑 Stopping existing containers..."
docker-compose down

# Start the services
echo "🏗️  Building and starting all services..."
docker-compose up -d --build

# Wait for services to be ready
echo "⏳ Waiting for services to be ready..."
sleep 30

# Check service status
echo "🔍 Checking service status..."
docker-compose ps

echo ""
echo "🎉 Deployment completed!"
echo ""
echo "📋 Service URLs:"
echo "   Frontend:     http://$HOST_IP:3000"
echo "   User Service: http://$HOST_IP:3001"
echo "   Hotel Service: http://$HOST_IP:3002"
echo "   Room Service: http://$HOST_IP:3003"
echo "   Booking Service: http://$HOST_IP:3004"
echo "   Payment Service: http://$HOST_IP:3005"
echo "   Notification Service: http://$HOST_IP:3006"
echo "   RabbitMQ Management: http://$HOST_IP:15672"
echo ""
echo "🔑 Test Credentials:"
echo "   Admin: admin@hotel.com / password123"
echo "   User 1: john@example.com / password123"
echo "   User 2: jane@example.com / password123"
echo ""
echo "ℹ️  To use a different IP address, run: ./deploy.sh <your-ip-address>"
